# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnPHBBxkR-MfkQhLRI4rFVPk8euHrYk_
"""

!pip --version

import numpy as np
import pandas as pd

l1 = [-17,"99",2.9,0,55]
# a1 = np.array([-17,"99",2.9,0,55])
a1 = np.array(l1)
a2 = np.ones(5, dtype=np.int64)
a3 = np.zeros(4, dtype=np.int64)
print(l1,type(l1))
print(a1,type(a1), a1.shape)
print(a2,type(a2), a2.shape)
print(a3,type(a3), a3.shape)

df1 = pd.DataFrame(
    [
        [10,7,91],[22,-17,4]
    ], index =[1,2], columns = ['python','java','php']
)
print(df1)

df1 = df1.rename(columns={'python' : 'pyt', 'java' : 'jav', 'php' : 'php'})

print(df1)
print(df1.iloc[1,1])
# df1.iloc[1,1] = 17
# df1.iloc[0,2] = 19
df1.loc[2,'jav'] = 17
df1.loc[1,'php'] = 19
print(df1)

import seaborn as sns

titanic = sns.load_dataset('titanic')
# print(titanic.info)
# print(titanic.head(5))
# print(titanic.tail(5))
print(titanic.query('age>=70'))

